### ISSUE TITLE
21-CN-EN-Translation-BERT don't work.

### ISSUE THREAD

**Issue by gaoxuezhao** [dragen1860/TensorFlow2.0Tutorials#21]
(venv) 29:21-CN-EN-Translation-BERT gaojianhua$ python bert_train.py
WARNING: Logging before flag parsing goes to stderr.
W0820 10:24:03.213339 4518290880 dataset_builder.py:689] Using custom data configuration zh-en
{}
Downloading and preparing dataset wmt_translate (?? GiB) to /Users/gaojianhua/tensorflow_datasets/wmt_translate/zh-en/0.0.3...
Dl Completed...: 0 url [00:00, ? url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Extraction completed...: 0 file [00:00, ? file/s]

Extraction completed...: 0 file [00:00, ? file/s]

Traceback (most recent call last):
  File "bert_train.py", line 33, in <module>
    get_tokenizer(MAX_SEQ_LENGTH, BATCH_SIZE)
  File "/Users/gaojianhua/TensorFlow-2.x-Tutorials/21-CN-EN-Translation-BERT/tokenizer.py", line 322, in get_tokenizer
    builder.download_and_prepare()
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 287, in download_and_prepare
    download_config=download_config)
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 948, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 816, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 972, in _prepare_split
    example = self.info.features.encode_example(record)
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/features/features_dict.py", line 168, in encode_example
    in utils.zip_dict(self._feature_dict, example_dict)
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/features/features_dict.py", line 165, in <dictcomp>
    return {
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 67, in zip_dict
    yield key, tuple(d[key] for d in dicts)
  File "/Users/gaojianhua/venv/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 67, in <genexpr>
    yield key, tuple(d[key] for d in dicts)
KeyError: 'e'

**Comment by gaoxuezhao** [comment]
It seems to download a dataset, but fails.
