### ISSUE TITLE
运行import tensorflow as tf，出现如下错误

### ISSUE THREAD

**Issue by c0derm4n** [dragen1860/TensorFlow2.0Tutorials#3]
ImportError: Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

**Comment by dragen1860** [comment]
it should be your failure installtation of cudnn. refer to this tutorial: https://study.163.com/course/courseMain.htm?share=2&shareId=480000001847407&courseId=1209092816&_trace_c_p_k2_=a2d138f2949c4e69b900924cf88dbacf
