### ISSUE TITLE
Error in ColorBot

### ISSUE THREAD

**Issue by maggiezha** [dragen1860/TensorFlow2.0Tutorials#8]
I got this error when I run: python main.py 
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    main()
  File "main.py", line 69, in main
    data_dir=data_dir, url=SOURCE_TRAIN_URL, batch_size=batchsz)
  File "/home/maggie/TensorFlow-2.x-Tutorials/lesson19-ColorBot/utils.py", line 53, in load_dataset
    path = maybe_download(os.path.basename(url), data_dir, url)
  File "/home/maggie/TensorFlow-2.x-Tutorials/lesson19-ColorBot/utils.py", line 40, in maybe_download
    temp_file_name, _ = urllib.request.urlretrieve(source_url)
AttributeError: 'module' object has no attribute 'request'

**Comment by dragen1860** [comment]
use python 3.7.
