### ISSUE TITLE
Pixel2Pixel: IOError: [Errno 2] No such file or directory: 'images/epoch0.png'

### ISSUE THREAD

**Issue by maggiezha** [dragen1860/TensorFlow2.0Tutorials#9]

**Comment by maggiezha** [comment]
when I run: python main.py
Traceback (most recent call last):
  File "main.py", line 241, in <module>
    main()
  File "main.py", line 224, in main
    generate_images(generator, input_image, target, epoch)
  File "main.py", line 175, in generate_images
    plt.savefig('images/epoch%d.png'%epoch)
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 695, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 94, in print_figure
    super(FigureCanvasQTAgg, self).print_figure(*args, **kwargs)
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/home/maggie/anaconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 626, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/maggie/anaconda2/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 611, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
IOError: [Errno 2] No such file or directory: 'images/epoch0.png'

**Comment by dragen1860** [comment]
`mkdir images`
Pls use python 3.x
